#ifndef ERRORS_H
#define ERRORS_H

#define OK 0
#define ARGS_ERROR 1
#define FILE_OPEN_ERROR 2
#define EMPTY_FILTR_ARRAY 3
#define MEMORY_ALLOCATION_ERROR 4
#define CLOSE_FILE_ERROR 5
#define EMPTY_SRC_ARRAY_ERROR 6
#define NO_ELEMENTS_BETWEEN_ERROR 7

#endif // ERRORS_H
